-- ================================================================
-- TOWN PARCEL — COMPLETE SUPABASE DATABASE SETUP
-- ================================================================
-- Run this entire script once in Supabase Dashboard → SQL Editor.
-- Safe to re-run: uses IF NOT EXISTS / DROP POLICY IF EXISTS
-- throughout, so running it again will not duplicate anything
-- or error out on tables/policies that already exist.
--
-- Covers:
--   1. customer_bookings          (existing — unchanged schema)
--   2. partner_registrations      (existing — unchanged schema)
--   3. rider_registrations        (existing — unchanged schema)
--   4. contact_messages           (existing — unchanged schema)
--   5. personal_delivery_bookings (NEW — for the Personal Delivery
--                                   booking form)
--
-- Access model (same pattern across all 5 tables):
--   - Public (anon key, used by your website forms) → INSERT ONLY
--   - Logged-in admins (authenticated, used by /admin) → SELECT,
--     UPDATE, DELETE
--   - Nobody can read/edit/delete via the public anon key.
-- ================================================================


-- ================================================================
-- 1. CUSTOMER_BOOKINGS  (business/shop delivery bookings)
-- ================================================================
create table if not exists public.customer_bookings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  booking_id text null,
  shop_name text null,
  shop_address text null,
  shop_phone text null,
  customer_name text null,
  customer_phone text null,
  delivery_address text null,
  pickup_item text null,
  item_quantity text null,
  item_value numeric null,
  payment_status text null,
  payment_method text null,
  delivery_charge numeric null,
  booking_status text null default 'pending',
  rider_name text null,
  rider_phone text null,
  notes text null,
  constraint customer_bookings_pkey primary key (id)
);

create index if not exists idx_customer_bookings_booking_id on public.customer_bookings (booking_id);
create index if not exists idx_customer_bookings_status on public.customer_bookings (booking_status);
create index if not exists idx_customer_bookings_customer_phone on public.customer_bookings (customer_phone);
create index if not exists idx_customer_bookings_created_at on public.customer_bookings (created_at desc);


-- ================================================================
-- 2. PARTNER_REGISTRATIONS  (business partner applications)
-- ================================================================
create table if not exists public.partner_registrations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  partner_id text null,
  business_name text null,
  owner_name text null,
  mobile text null,
  whatsapp text null,
  email text null,
  business_type text null,
  business_address text null,
  area text null,
  city text null,
  pincode text null,
  gst_number text null,
  business_license text null,
  opening_time text null,
  closing_time text null,
  pickup_contact text null,
  pickup_phone text null,
  bank_account_name text null,
  bank_account_number text null,
  ifsc_code text null,
  upi_id text null,
  status text null default 'pending',
  remarks text null,
  constraint partner_registrations_pkey primary key (id)
);

create index if not exists idx_partner_registrations_status on public.partner_registrations (status);
create index if not exists idx_partner_registrations_mobile on public.partner_registrations (mobile);
create index if not exists idx_partner_registrations_created_at on public.partner_registrations (created_at desc);


-- ================================================================
-- 3. RIDER_REGISTRATIONS  (delivery rider applications)
-- ================================================================
create table if not exists public.rider_registrations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  rider_id text null,
  full_name text null,
  mobile text null,
  whatsapp text null,
  email text null,
  date_of_birth date null,
  gender text null,
  address text null,
  city text null,
  pincode text null,
  service_area text null,
  vehicle_type text null,
  vehicle_number text null,
  driving_license_number text null,
  aadhar_number text null,
  emergency_conntact_number text null,
  emergency_contact_num text null,
  bank_account_name text null,
  bank_account_number text null,
  ifsc_code text null,
  upi_id text null,
  status text null default 'pending',
  remarks text null,
  constraint rider_registrations_pkey primary key (id)
);

create index if not exists idx_rider_registrations_status on public.rider_registrations (status);
create index if not exists idx_rider_registrations_mobile on public.rider_registrations (mobile);
create index if not exists idx_rider_registrations_created_at on public.rider_registrations (created_at desc);


-- ================================================================
-- 4. CONTACT_MESSAGES  (Contact Us form)
-- ================================================================
create table if not exists public.contact_messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  message_id text null,
  full_name text null,
  mobile text null,
  whatsapp text null,
  email text null,
  subject text null,
  message text null,
  preferred_contact text null,
  status text null default 'new',
  admin_notes text null,
  replied_at timestamp without time zone null,
  constraint contact_messages_pkey primary key (id)
);

create index if not exists idx_contact_messages_status on public.contact_messages (status);
create index if not exists idx_contact_messages_created_at on public.contact_messages (created_at desc);


-- ================================================================
-- 5. PERSONAL_DELIVERY_BOOKINGS  (NEW — personal/individual
--    delivery bookings: documents, gifts, parcels, medicines, etc.)
-- ================================================================
create table if not exists public.personal_delivery_bookings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  booking_id text null,
  customer_name text null,
  mobile text null,
  alternate_mobile text null,
  pickup_address text null,
  delivery_address text null,
  receiver_name text null,
  receiver_mobile text null,
  package_type text null,
  package_description text null,
  weight text null,
  pickup_time text null,
  payment_method text null,
  instructions text null,
  rider_name text null,
  rider_phone text null,
  status text null default 'pending',
  constraint personal_delivery_bookings_pkey primary key (id)
);

create index if not exists idx_personal_delivery_bookings_booking_id on public.personal_delivery_bookings (booking_id);
create index if not exists idx_personal_delivery_bookings_status on public.personal_delivery_bookings (status);
create index if not exists idx_personal_delivery_bookings_mobile on public.personal_delivery_bookings (mobile);
create index if not exists idx_personal_delivery_bookings_created_at on public.personal_delivery_bookings (created_at desc);

-- Note on "relationships": rider_name / rider_phone are kept as
-- plain text fields (not a foreign key to rider_registrations),
-- matching the same pattern already used in customer_bookings.
-- This keeps assignment simple and avoids requiring every rider
-- to have a formal linked record before they can be assigned.


-- ================================================================
-- 6. APP_SETTINGS  (single-row config used by the admin Settings page)
-- ================================================================
create table if not exists public.app_settings (
  id smallint generated always as identity not null,
  company_name text default 'Town Parcel',
  logo_url text,
  phone text,
  whatsapp text,
  email text,
  address text,
  working_hours text default 'Monday – Sunday, 8:00 AM – 9:00 PM',
  delivery_charge numeric,
  minimum_order numeric,
  maximum_distance_km numeric,
  service_areas text,
  updated_at timestamp with time zone default now(),
  constraint app_settings_pkey primary key (id),
  constraint app_settings_single_row check (id = 1)
);

insert into public.app_settings (id, company_name, phone, whatsapp, email, address, working_hours, service_areas)
select 1, 'Town Parcel', '+91 97316 74173', '+91 97316 74173', 'contact@townparcel.in',
       'Sagara, Karnataka', 'Monday – Sunday, 8:00 AM – 9:00 PM', 'Sagara, Karnataka'
where not exists (select 1 from public.app_settings where id = 1);

alter table public.app_settings enable row level security;

-- Only logged-in admins can read or update settings (no public access needed).
drop policy if exists "Allow authenticated select on app_settings" on public.app_settings;
create policy "Allow authenticated select on app_settings"
  on public.app_settings for select to authenticated using (true);
drop policy if exists "Allow authenticated update on app_settings" on public.app_settings;
create policy "Allow authenticated update on app_settings"
  on public.app_settings for update to authenticated using (true) with check (true);


-- ================================================================
-- ROW LEVEL SECURITY — PUBLIC INSERT-ONLY (website forms)
-- ================================================================

-- customer_bookings
alter table public.customer_bookings enable row level security;
drop policy if exists "Allow public insert on customer_bookings" on public.customer_bookings;
create policy "Allow public insert on customer_bookings"
  on public.customer_bookings for insert to anon with check (true);

-- partner_registrations
alter table public.partner_registrations enable row level security;
drop policy if exists "Allow public insert on partner_registrations" on public.partner_registrations;
create policy "Allow public insert on partner_registrations"
  on public.partner_registrations for insert to anon with check (true);

-- rider_registrations
alter table public.rider_registrations enable row level security;
drop policy if exists "Allow public insert on rider_registrations" on public.rider_registrations;
create policy "Allow public insert on rider_registrations"
  on public.rider_registrations for insert to anon with check (true);

-- contact_messages
alter table public.contact_messages enable row level security;
drop policy if exists "Allow public insert on contact_messages" on public.contact_messages;
create policy "Allow public insert on contact_messages"
  on public.contact_messages for insert to anon with check (true);

-- personal_delivery_bookings
alter table public.personal_delivery_bookings enable row level security;
drop policy if exists "Allow public insert on personal_delivery_bookings" on public.personal_delivery_bookings;
create policy "Allow public insert on personal_delivery_bookings"
  on public.personal_delivery_bookings for insert to anon with check (true);


-- ================================================================
-- ROW LEVEL SECURITY — ADMIN ACCESS (authenticated only)
-- ================================================================
-- Used by /admin (logged-in Supabase Auth users). Public anon
-- key still cannot read, edit, or delete anything.

-- customer_bookings
drop policy if exists "Allow authenticated select on customer_bookings" on public.customer_bookings;
create policy "Allow authenticated select on customer_bookings"
  on public.customer_bookings for select to authenticated using (true);
drop policy if exists "Allow authenticated update on customer_bookings" on public.customer_bookings;
create policy "Allow authenticated update on customer_bookings"
  on public.customer_bookings for update to authenticated using (true) with check (true);
drop policy if exists "Allow authenticated delete on customer_bookings" on public.customer_bookings;
create policy "Allow authenticated delete on customer_bookings"
  on public.customer_bookings for delete to authenticated using (true);

-- partner_registrations
drop policy if exists "Allow authenticated select on partner_registrations" on public.partner_registrations;
create policy "Allow authenticated select on partner_registrations"
  on public.partner_registrations for select to authenticated using (true);
drop policy if exists "Allow authenticated update on partner_registrations" on public.partner_registrations;
create policy "Allow authenticated update on partner_registrations"
  on public.partner_registrations for update to authenticated using (true) with check (true);
drop policy if exists "Allow authenticated delete on partner_registrations" on public.partner_registrations;
create policy "Allow authenticated delete on partner_registrations"
  on public.partner_registrations for delete to authenticated using (true);

-- rider_registrations
drop policy if exists "Allow authenticated select on rider_registrations" on public.rider_registrations;
create policy "Allow authenticated select on rider_registrations"
  on public.rider_registrations for select to authenticated using (true);
drop policy if exists "Allow authenticated update on rider_registrations" on public.rider_registrations;
create policy "Allow authenticated update on rider_registrations"
  on public.rider_registrations for update to authenticated using (true) with check (true);
drop policy if exists "Allow authenticated delete on rider_registrations" on public.rider_registrations;
create policy "Allow authenticated delete on rider_registrations"
  on public.rider_registrations for delete to authenticated using (true);

-- contact_messages
drop policy if exists "Allow authenticated select on contact_messages" on public.contact_messages;
create policy "Allow authenticated select on contact_messages"
  on public.contact_messages for select to authenticated using (true);
drop policy if exists "Allow authenticated update on contact_messages" on public.contact_messages;
create policy "Allow authenticated update on contact_messages"
  on public.contact_messages for update to authenticated using (true) with check (true);
drop policy if exists "Allow authenticated delete on contact_messages" on public.contact_messages;
create policy "Allow authenticated delete on contact_messages"
  on public.contact_messages for delete to authenticated using (true);

-- personal_delivery_bookings
drop policy if exists "Allow authenticated select on personal_delivery_bookings" on public.personal_delivery_bookings;
create policy "Allow authenticated select on personal_delivery_bookings"
  on public.personal_delivery_bookings for select to authenticated using (true);
drop policy if exists "Allow authenticated update on personal_delivery_bookings" on public.personal_delivery_bookings;
create policy "Allow authenticated update on personal_delivery_bookings"
  on public.personal_delivery_bookings for update to authenticated using (true) with check (true);
drop policy if exists "Allow authenticated delete on personal_delivery_bookings" on public.personal_delivery_bookings;
create policy "Allow authenticated delete on personal_delivery_bookings"
  on public.personal_delivery_bookings for delete to authenticated using (true);


-- ================================================================
-- COLUMN REFERENCE — for matching website form fields exactly
-- ================================================================
-- customer_bookings:
--   booking_id, shop_name, shop_address, shop_phone,
--   customer_name, customer_phone, delivery_address,
--   pickup_item, item_quantity, item_value (numeric),
--   payment_status, payment_method, notes, booking_status
--
-- partner_registrations:
--   partner_id, business_name, owner_name, mobile, whatsapp,
--   email, business_type, business_address, area, city,
--   pincode, remarks, status
--
-- rider_registrations:
--   rider_id, full_name, mobile, whatsapp, email,
--   date_of_birth, gender, address, city, pincode,
--   service_area, vehicle_type, vehicle_number,
--   driving_license_number, aadhar_number,
--   emergency_conntact_number, remarks, status
--
-- contact_messages:
--   message_id, full_name, mobile, email, subject, message,
--   preferred_contact, status, admin_notes
--
-- personal_delivery_bookings (NEW — matches the Personal
-- Delivery form fields exactly):
--   booking_id, customer_name, mobile, alternate_mobile,
--   pickup_address, delivery_address, receiver_name,
--   receiver_mobile, package_type, package_description,
--   weight, pickup_time, payment_method, instructions,
--   rider_name, rider_phone, status
-- ================================================================
